version: 2
models:
- name: dim_gasstation
  columns:
  - name: gas_station_id
    data_tests:
    - not_null
    - unique
- name: dim_customer
  columns:
  - name: customer_id
    data_tests:
    - not_null
    - unique
- name: dim_employee
  columns:
  - name: employee_id
    data_tests:
    - not_null
    - unique
- name: dim_products
  columns:
  - name: product_id
    data_tests:
    - not_null
    - unique
- name: dim_date
  columns:
  - name: date_id
    data_tests:
    - not_null
    - unique
- name: dim_hour
  columns:
  - name: hour_id
    data_tests:
    - not_null
    - unique
- name: dim_tanks
  columns:
  - name: tank_id
    data_tests:
    - not_null
    - unique
  - name: gas_station_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_gasstation')
          field: gas_station_id
  - name: product_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_products')
          field: product_id
  - name: capacity
    data_tests:
    - not_null
- name: fact_invoices
  columns:
  - name: invoice_id
    data_tests:
    - not_null
    - unique
  - name: gas_station_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_gasstation')
          field: gas_station_id
  - name: customer_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_customer')
          field: customer_id
  - name: employee_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_employee')
          field: employee_id
  - name: date_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_date')
          field: date_id
  - name: hour_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_hour')
          field: hour_id
  - name: total_amount
    data_tests:
    - not_null
  - name: issue_timestamp
    data_tests:
    - not_null
  - name: payment_method
    data_tests:
    - not_null
- name: fact_sales
  columns:
  - name: invoice_detail_id
    data_tests:
    - not_null
    - unique
  - name: gas_station_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_gasstation')
          field: gas_station_id
  - name: customer_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_customer')
          field: customer_id
  - name: employee_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_employee')
          field: employee_id
  - name: date_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_date')
          field: date_id
  - name: hour_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_hour')
          field: hour_id
  - name: invoice_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('fact_invoices')
          field: invoice_id
  - name: product_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_products')
          field: product_id
  - name: quantity_sold
    data_tests:
    - not_null
  - name: selling_price
    data_tests:
    - not_null
  - name: sales_amount
    data_tests:
    - not_null
- name: fact_inventory
  columns:
  - name: transaction_id
    data_tests:
    - not_null
    - unique
  - name: tank_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_tanks')
          field: tank_id
  - name: gas_station_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_gasstation')
          field: gas_station_id
  - name: product_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_products')
          field: product_id
  - name: date_id
    data_tests:
    - not_null
    - relationships:
        arguments:
          to: ref('dim_date')
          field: date_id
  - name: quantity_in
    data_tests:
    - not_null
  - name: quantity_out
    data_tests:
    - not_null
  - name: remaining_quantity
    data_tests:
    - not_null
  - name: transaction_timestamp
    data_tests:
    - not_null
